#!/usr/bin/env python3
"""
generate_session.py — Generate a MIDI autosampler file AND a pre-filled metadata.toml.

Usage:
    python generate_session.py -X 4 -N 1 -H 10.0 -R 0.5 -o my_instrument

Output:
    my_instrument.mid           — feed to your virtual instrument and render to WAV
    my_instrument/metadata.toml — pre-filled with recording settings; fill in the rest

Optional args:
    --start-note  INT   Lowest MIDI note to record (default: 21 = A0)
    --end-note    INT   Highest MIDI note to record (default: 108 = C8)
    --out-dir     DIR   Directory to write metadata.toml into (default: same name as -o)
"""

import argparse
import math
import os
import sys

try:
    from midiutil import MIDIFile
except ImportError:
    print("midiutil not found. Run: pip install midiutil")
    sys.exit(1)


PIANO_LOW  = 21
PIANO_HIGH = 108
NOTE_NAMES = ["C", "Cs", "D", "Ds", "E", "F", "Fs", "G", "Gs", "A", "As", "B"]


def midi_note_to_name(midi_note: int) -> str:
    octave = (midi_note // 12) - 1
    return f"{NOTE_NAMES[midi_note % 12]}{octave}"


def compute_velocities(x: int) -> list[int]:
    if x == 1:
        return [127]
    if x == 2:
        return [1, 127]
    velocities = []
    for i in range(x):
        if i == 0:
            velocities.append(1)
        elif i == x - 1:
            velocities.append(127)
        else:
            velocities.append(round(1 + i * (126 / (x - 1))))
    return velocities


def generate_midi(x: int, n: int, h: float, r: float,
                  start_note: int, end_note: int, output_path: str):
    bpm = 120.0
    beats_per_second = bpm / 60.0
    hold_beats    = h * beats_per_second
    release_beats = r * beats_per_second
    spacing_beats = hold_beats + release_beats

    notes      = list(range(start_note, end_note + 1, n))
    velocities = compute_velocities(x)
    total      = len(notes) * len(velocities)

    print(f"Generating MIDI:")
    print(f"  Velocity layers (X): {x}  → {velocities}")
    print(f"  Semitone interval (N): {n}")
    print(f"  Hold time (H): {h}s   Release time (R): {r}s")
    print(f"  Note range: {midi_note_to_name(start_note)} ({start_note}) "
          f"– {midi_note_to_name(end_note)} ({end_note})")
    print(f"  Notes to sample: {len(notes)}")
    print(f"  Total events: {total}  "
          f"({total * (h + r):.1f}s / {total * (h + r) / 60:.1f} min)")

    midi = MIDIFile(1)
    midi.addTempo(0, 0, bpm)
    midi.addTrackName(0, 0, "Autosample")

    beat = 0.0
    for note in notes:
        for vel in velocities:
            midi.addNote(track=0, channel=0, pitch=note,
                         time=beat, duration=hold_beats, volume=vel)
            beat += spacing_beats

    with open(output_path, "wb") as f:
        midi.writeFile(f)
    print(f"\nMIDI written: {output_path}")


def generate_metadata(x: int, n: int, h: float, r: float,
                      start_note: int, end_note: int, output_path: str):
    content = f"""\
# Auto-Sampler CLI — Instrument Metadata
# Generated by generate_session.py — fill in the sections below.

# ─── RECORDING ───────────────────────────────────────────────────────────────
# These match the MIDI file that was generated alongside this metadata.toml.

velocity_layers   = {x}
semitone_interval = {n}
hold_time         = {h}
release_time      = {r}
start_note        = {start_note}     # {midi_note_to_name(start_note)}
end_note          = {end_note}     # {midi_note_to_name(end_note)}

# Only needed if release.wav was recorded with different hold/release timings.
# If omitted, the values above are reused for release.wav slicing.
# release_hold_time    = 0.5
# release_release_time = 1.0

# ─── OUTPUT SELECTION ────────────────────────────────────────────────────────

min_note             = {start_note}     # lowest MIDI note to include in output
max_note             = {end_note}     # highest MIDI note to include in output
note_percentage      = 100    # % of notes in range to keep (50 = evenly-spaced half)
velocity_layers_out  = {x}      # how many velocity layers in the output (1–{x})

# Optional: override velocity_layers_out with per-range layer counts.
# velocity_map = "0-63:1, 64-127:5"

# ─── CROSSFADE ───────────────────────────────────────────────────────────────

crossfade_percent = 20    # % of velocity zone width that overlaps adjacent layers
                          # 0 = hard boundaries, 50 = half of each zone overlaps

# ─── NORMALIZATION ───────────────────────────────────────────────────────────

normalize       = true
normalize_mode  = "lufs"   # "lufs" | "rms" | "velocity"

normalize_target_lufs        = -18.0
peak_ceiling_db              = -1.0
velocity_dynamic_range_db    = 40.0

# ─── PLAYBACK / SFZ ──────────────────────────────────────────────────────────

ampeg_release      = 0.5
loop_crossfade_ms  = 20.0

# ─── TRANSIENT SHAPER ────────────────────────────────────────────────────────

enable_transient_shaper = false
transient_attack_db     = 6.0
transient_sustain_db    = 0.0
transient_speed_ms      = 10.0

# ─── ADVANCED ────────────────────────────────────────────────────────────────

pre_trim_ms      = 0.0
collapse_to_mono = false
"""
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        f.write(content)
    print(f"Metadata written: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate a MIDI autosampler file + pre-filled metadata.toml."
    )
    parser.add_argument("-X", type=int, required=True,
                        help="Number of velocity layers per note")
    parser.add_argument("-N", type=int, required=True,
                        help="Semitone interval (1=every key, 2=every other, etc.)")
    parser.add_argument("-H", type=float, required=True,
                        help="Hold time in seconds (note-on duration)")
    parser.add_argument("-R", type=float, required=True,
                        help="Release time in seconds (silence after note-off)")
    parser.add_argument("-o", "--output", type=str, required=True,
                        help="Output stem name (writes <name>.mid and <name>/metadata.toml)")
    parser.add_argument("--start-note", type=int, default=PIANO_LOW,
                        help=f"Lowest MIDI note to record (default: {PIANO_LOW} = A0)")
    parser.add_argument("--end-note", type=int, default=PIANO_HIGH,
                        help=f"Highest MIDI note to record (default: {PIANO_HIGH} = C8)")
    parser.add_argument("--out-dir", type=str, default=None,
                        help="Directory for metadata.toml (default: ./<output>/)")

    args = parser.parse_args()

    if args.X < 1:      parser.error("X must be >= 1")
    if args.N < 1:      parser.error("N must be >= 1")
    if args.H <= 0:     parser.error("H must be positive")
    if args.R < 0:      parser.error("R must be non-negative")
    if args.start_note < 0 or args.end_note > 127 or args.start_note >= args.end_note:
        parser.error("start-note / end-note out of range or inverted")

    midi_path = args.output if args.output.endswith(".mid") else args.output + ".mid"

    meta_dir  = args.out_dir if args.out_dir else os.path.splitext(args.output)[0]
    meta_path = os.path.join(meta_dir, "metadata.toml")

    generate_midi(args.X, args.N, args.H, args.R,
                  args.start_note, args.end_note, midi_path)
    generate_metadata(args.X, args.N, args.H, args.R,
                      args.start_note, args.end_note, meta_path)

    print(f"\nNext steps:")
    print(f"  1. Load {midi_path} into your DAW and render the instrument to WAV")
    print(f"  2. Save the render as {meta_dir}/sustain.wav")
    print(f"  3. (Optional) record release tails → {meta_dir}/release.wav")
    print(f"  4. Fill in any remaining fields in {meta_path}")
    print(f"  5. Run: python main.py <parent_dir>")


if __name__ == "__main__":
    main()
