#!/usr/bin/env python3
"""
generate_input_toml.py — Helper script to generate input.toml for uniform recordings.

For non-uniform recordings (different velocities or lengths per note), use this
as a starting point and edit the output file manually.

Usage examples:

  # 88-note piano, 8 uniform velocity layers, 10s hold, 0.5s tail
  python generate_input_toml.py \\
      --notes 21-108:1 \\
      --velocities 1,18,36,54,72,90,108,127 \\
      --hold-s 10.0 \\
      --tail-s 0.5

  # With release tails (different timing)
  python generate_input_toml.py \\
      --notes 21-108:1 \\
      --velocities 1,64,127 \\
      --hold-s 10.0 --tail-s 0.5 \\
      --with-release \\
      --release-hold-s 0.3 --release-tail-s 3.0

  # Every 3 semitones, single velocity
  python generate_input_toml.py \\
      --notes 21-108:3 \\
      --velocities 127 \\
      --hold-s 8.0 --tail-s 1.0 \\
      --output my_instrument/input.toml

Arguments:
  --notes RANGE       Note range as start-end:interval  (e.g. 21-108:1)
  --velocities LIST   Comma-separated MIDI velocity values (e.g. 1,64,127)
  --hold-s FLOAT      Seconds each note was held
  --tail-s FLOAT      Seconds of decay/silence after note-off
  --with-release      Also add release tail entries after all sustain entries
  --release-hold-s FLOAT   Hold time for release recordings (default: same as --hold-s)
  --release-tail-s FLOAT   Tail time for release recordings (default: same as --tail-s)
  --collapse-to-mono  Set collapse_to_mono = true in output
  --output PATH       Output file path (default: input.toml)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def parse_notes(spec: str) -> list[int]:
    """Parse 'start-end:interval' into a sorted list of MIDI notes."""
    try:
        range_part, _, interval_str = spec.partition(":")
        lo_str, _, hi_str = range_part.partition("-")
        lo, hi, interval = int(lo_str), int(hi_str), int(interval_str) if interval_str else 1
    except ValueError:
        raise ValueError(
            f"Invalid --notes format '{spec}'. Expected 'start-end:interval', e.g. '21-108:1'"
        )
    if not (0 <= lo <= 127 and 0 <= hi <= 127):
        raise ValueError(f"Note values must be 0–127, got {lo}–{hi}")
    if lo > hi:
        raise ValueError(f"start note ({lo}) must be <= end note ({hi})")
    if interval < 1:
        raise ValueError(f"Interval must be >= 1, got {interval}")
    return list(range(lo, hi + 1, interval))


def parse_velocities(spec: str) -> list[int]:
    """Parse '1,64,127' into a sorted list of MIDI velocities."""
    try:
        vels = sorted(int(v.strip()) for v in spec.split(","))
    except ValueError:
        raise ValueError(
            f"Invalid --velocities format '{spec}'. Expected comma-separated integers, e.g. '1,64,127'"
        )
    for v in vels:
        if not (1 <= v <= 127):
            raise ValueError(f"Velocity {v} out of range 1–127")
    return vels


def generate_toml(
    notes: list[int],
    velocities: list[int],
    hold_s: float,
    tail_s: float,
    with_release: bool,
    release_hold_s: float,
    release_tail_s: float,
    collapse_to_mono: bool,
) -> str:
    n_sus = len(notes) * len(velocities)
    n_rel = n_sus if with_release else 0
    header = (
        "# Auto-Sampler CLI — Input Sample Manifest\n"
        "# Generated by generate_input_toml.py\n"
        f"# {len(notes)} note(s) × {len(velocities)} velocity layer(s)"
        + (f" + {n_rel} release tail(s)" if with_release else "") + "\n"
        "\n"
        f"collapse_to_mono = {'true' if collapse_to_mono else 'false'}\n"
        "\n"
    )

    entries = []
    for note in notes:
        for vel in velocities:
            entries.append(
                f"  {{note={note}, velocity={vel}, hold_s={hold_s}, tail_s={tail_s}, is_release=false}}"
            )

    if with_release:
        for note in notes:
            for vel in velocities:
                entries.append(
                    f"  {{note={note}, velocity={vel}, hold_s={release_hold_s}, tail_s={release_tail_s}, is_release=true}}"
                )

    return header + "samples = [\n" + ",\n".join(entries) + "\n]\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate input.toml for a uniformly-recorded instrument.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__.split("Arguments:")[0].strip(),
    )
    parser.add_argument("--notes",      required=True, help="Note range: start-end:interval (e.g. 21-108:1)")
    parser.add_argument("--velocities", required=True, help="Comma-separated velocities (e.g. 1,64,127)")
    parser.add_argument("--hold-s",     required=True, type=float, help="Hold time in seconds")
    parser.add_argument("--tail-s",     required=True, type=float, help="Tail/silence time in seconds")
    parser.add_argument("--with-release",    action="store_true", help="Add release tail entries")
    parser.add_argument("--release-hold-s",  type=float, default=None, help="Hold time for release (default: --hold-s)")
    parser.add_argument("--release-tail-s",  type=float, default=None, help="Tail time for release (default: --tail-s)")
    parser.add_argument("--collapse-to-mono", action="store_true", help="Set collapse_to_mono=true")
    parser.add_argument("--output",     default="input.toml", help="Output file path (default: input.toml)")

    args = parser.parse_args()

    try:
        notes      = parse_notes(args.notes)
        velocities = parse_velocities(args.velocities)
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.hold_s <= 0:
        print("ERROR: --hold-s must be > 0", file=sys.stderr)
        return 1
    if args.tail_s < 0:
        print("ERROR: --tail-s must be >= 0", file=sys.stderr)
        return 1

    release_hold_s = args.release_hold_s if args.release_hold_s is not None else args.hold_s
    release_tail_s = args.release_tail_s if args.release_tail_s is not None else args.tail_s

    toml_text = generate_toml(
        notes=notes,
        velocities=velocities,
        hold_s=args.hold_s,
        tail_s=args.tail_s,
        with_release=args.with_release,
        release_hold_s=release_hold_s,
        release_tail_s=release_tail_s,
        collapse_to_mono=args.collapse_to_mono,
    )

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(toml_text, encoding="utf-8")

    n_sustain = len(notes) * len(velocities)
    n_release = n_sustain if args.with_release else 0
    print(f"Written: {out_path}")
    print(f"  {len(notes)} notes × {len(velocities)} velocities = {n_sustain} sustain entries", end="")
    print(f" + {n_release} release entries" if n_release else "")
    total_s = sum(
        args.hold_s + args.tail_s for _ in range(n_sustain)
    ) + sum(
        release_hold_s + release_tail_s for _ in range(n_release)
    )
    print(f"  Estimated samples.flac length: {total_s:.1f} s ({total_s / 60:.1f} min)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
