"""
input_module.py — Load an instrument folder into InstrumentData.

Each instrument folder must contain:
    metadata.txt   — recording/processing parameters
    sustain.wav    — long WAV of all sustain samples (required)
    release.wav    — long WAV of all release tails (optional)

The long WAVs were generated by playing generate_midi.py's MIDI into a plugin,
then rendering. This module slices them back into individual per-(note, velocity)
Sample objects in memory — no intermediate files are written.

Public API:
    load_instrument(folder_path: str | Path) -> InstrumentData
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Optional

import numpy as np
import soundfile as sf

from .data import InstrumentData, InstrumentMeta, Sample
from .metadata_parser import parse_metadata


# ---------------------------------------------------------------------------
# Helpers (mirrors V2 chop_samples.py / generate_midi.py logic)
# ---------------------------------------------------------------------------

def _compute_velocities(x: int) -> List[int]:
    """Return x evenly-spaced MIDI velocities from 1 to 127, inclusive."""
    if x == 1:
        return [127]
    if x == 2:
        return [1, 127]
    velocities = []
    for i in range(x):
        if i == 0:
            velocities.append(1)
        elif i == x - 1:
            velocities.append(127)
        else:
            velocities.append(round(1 + i * (126 / (x - 1))))
    return velocities


def _get_recorded_notes(start_note: int, end_note: int, semitone_interval: int) -> List[int]:
    """Return list of MIDI notes that were recorded, stepping by semitone_interval."""
    return list(range(start_note, end_note + 1, semitone_interval))


def _to_mono(audio: np.ndarray) -> np.ndarray:
    """Mix a (n_frames, n_channels) or (n_frames,) array down to (n_frames,)."""
    if audio.ndim == 1:
        return audio
    return audio.mean(axis=1)


def _slice_wav(
    audio: np.ndarray,
    sr: int,
    notes: List[int],
    velocities: List[int],
    hold_time: float,
    release_time: float,
    extract_release: bool,
    min_note: int,
    max_note: int,
    collapse_to_mono: bool,
) -> List[Sample]:
    """
    Slice a long rendered WAV array into individual Sample objects.

    Args:
        audio:            Full WAV as numpy array, shape (n_frames,) or (n_frames, n_ch).
        sr:               Sample rate in Hz.
        notes:            Ordered list of MIDI notes that were recorded.
        velocities:       Ordered list of MIDI velocities that were recorded.
        hold_time:        Seconds each note was held (sustain portion).
        release_time:     Seconds of silence/tail after note-off (release portion).
        extract_release:  If True, extract the tail (after note-off);
                          if False, extract the sustain (during note-on).
        min_note:         Only include notes >= min_note.
        max_note:         Only include notes <= max_note.
        collapse_to_mono: If True, convert each slice to mono.

    Returns:
        List of Sample objects, one per (note, velocity) pair within [min_note, max_note].
    """
    note_duration = hold_time + release_time
    frames_hold = int(round(hold_time * sr))
    frames_release = int(round(release_time * sr))
    total_frames = audio.shape[0]

    samples: List[Sample] = []
    event_index = 0

    for note in notes:
        for vel in velocities:
            event_start = int(round(event_index * note_duration * sr))

            if extract_release:
                slice_start = event_start + frames_hold
                slice_len = frames_release
            else:
                slice_start = event_start
                slice_len = frames_hold

            slice_end = slice_start + slice_len

            # Skip if this note is outside our output range
            # (we still need to advance event_index for correct offsets)
            if min_note <= note <= max_note:
                # Bounds-clamp: if the WAV is shorter than expected, take what we have
                if slice_start >= total_frames:
                    # Nothing to extract — emit a silent sample rather than crash
                    chunk = np.zeros(max(slice_len, 1), dtype=np.float64)
                else:
                    actual_end = min(slice_end, total_frames)
                    if audio.ndim == 1:
                        chunk = audio[slice_start:actual_end].astype(np.float64)
                    else:
                        chunk = audio[slice_start:actual_end].astype(np.float64)

                    # Pad with zeros if the clip ended early
                    if chunk.shape[0] < slice_len:
                        if chunk.ndim == 1:
                            chunk = np.pad(chunk, (0, slice_len - chunk.shape[0]))
                        else:
                            chunk = np.pad(chunk, ((0, slice_len - chunk.shape[0]), (0, 0)))

                # Apply mono collapse
                if collapse_to_mono:
                    chunk = _to_mono(chunk)
                elif chunk.ndim == 2 and chunk.shape[1] == 1:
                    # Single-channel 2-D → squeeze to 1-D
                    chunk = chunk[:, 0]

                samples.append(Sample(
                    midi_note=note,
                    velocity=vel,
                    audio=chunk,
                    sr=sr,
                ))

            event_index += 1

    return samples


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def load_instrument(folder_path: str | Path) -> InstrumentData:
    """
    Load an instrument folder into an InstrumentData ready for the pipeline.

    Steps:
      1. Parse metadata.txt → InstrumentMeta
      2. Load sustain.wav, slice into sustain Samples filtered to [min_note, max_note]
      3. Load release.wav (if present), slice into release Samples
      4. Return InstrumentData(sustain, release, meta)

    Args:
        folder_path: Path to the instrument folder containing metadata.txt
                     and sustain.wav (and optionally release.wav).

    Returns:
        InstrumentData populated with all sliced samples.

    Raises:
        FileNotFoundError:  if metadata.txt or sustain.wav is missing.
        MetadataError:      if metadata.txt is invalid.
        RuntimeError:       if the WAV file cannot be read.
    """
    folder = Path(folder_path)

    meta_path = folder / "metadata.txt"
    sustain_path = folder / "sustain.wav"
    release_path = folder / "release.wav"

    if not sustain_path.exists():
        raise FileNotFoundError(f"sustain.wav not found in: {folder}")

    meta: InstrumentMeta = parse_metadata(meta_path)

    notes = _get_recorded_notes(meta.start_note, meta.end_note, meta.semitone_interval)
    velocities = _compute_velocities(meta.velocity_layers)

    # --- Sustain ---
    sustain_audio, sustain_sr = sf.read(str(sustain_path), dtype="float64", always_2d=False)
    sustain_samples = _slice_wav(
        audio=sustain_audio,
        sr=sustain_sr,
        notes=notes,
        velocities=velocities,
        hold_time=meta.hold_time,
        release_time=meta.release_time,
        extract_release=False,
        min_note=meta.min_note,
        max_note=meta.max_note,
        collapse_to_mono=meta.collapse_to_mono,
    )

    # --- Release (optional) ---
    release_samples: List[Sample] = []
    if release_path.exists():
        release_audio, release_sr = sf.read(str(release_path), dtype="float64", always_2d=False)
        release_samples = _slice_wav(
            audio=release_audio,
            sr=release_sr,
            notes=notes,
            velocities=velocities,
            hold_time=meta.effective_release_hold_time(),
            release_time=meta.effective_release_release_time(),
            extract_release=True,
            min_note=meta.min_note,
            max_note=meta.max_note,
            collapse_to_mono=meta.collapse_to_mono,
        )

    return InstrumentData(
        sustain=sustain_samples,
        release=release_samples,
        meta=meta,
    )
